name: Build and Deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PUBLISH_PATH: '.'
  AZURE_WEB_APP: 'vsaspnetcoreapp-demo'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o '${{env.PUBLISH_PATH}}/publish'
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: '${{env.AZURE_WEB_APP}}'
        publish-profile: '${{secrets.publish_profile}}'
        package: '${{env.PUBLISH_PATH}}/publish'
        
